site_name: uSync

repo_url: https://github.com/KevinJump/uSync/
edit_uri: edit/v4_master/docs/

pages:
    - 'Introduction': 'index.md'
    - 'Installation': 'install.md'
    - 'Getting Started' : 'getting-started.md'
    - 'Config':
        - 'BackOffice Config' : 'backoffice-config.md'
        - 'Handler Config' : 'handler-config.md'
        - 'Core Config' : 'core-config.md'
    - 'Advanced':
        - 'Actions File' : 'action-file.md'
    - 'uSync.ContentEdition': 'contentedition.md'
    - 'The uSync Project' : 'usync-project.md'
    - 'Versions' : 'versions.md'

theme: readthedocs
